---
 - name: Desinstalar Apache, wordpress - mysql
   hosts: maquinas
   become: yes
   tasks:
   - name: parando apache
     ansible.builtin.service:
       name: apache2
       state: stopped

   - name: parar mysql
     ansible.builtin.service:
       name: mysql
       state: stopped
    
   - name: desinstalar apache
     apt:
        name: apache2
        state: absent

   - name: eliminando archivos de configuracion de apache
     ansible.builtin.file:
       path: /etc/apache2
       state: absent
       owner: root
       group: root
       force: yes

   - name: eliminando los archivos /var/www/html
     ansible.builtin.file:
       path: /var/www/html
       state: absent

     
   - name: desinstalar mysql y todas las dependencias
     apt:
       name: "{{ item }}"
       state: absent
     loop:   
        - ghostscript 
        - libapache2-mod-php
        - mysql-server
        - php
        - php-bcmath
        - php-curl
        - php-imagick
        - php-intl
        - php-json
        - php-mbstring
        - php-mysql
        - php-xml
        - php-zip
        - php-gd
        - python3-mysqldb 
        - apache2
        - apache2-bin
        - apache2-data
        - apache2-utils
        - libapache2-mod-php8.1 
        - mysql-client-8.0
        - mysql-client-core-8.0 
        - mysql-common
        - mysql-server-8.0
        - mysql-server-core-8.0
        - php8.1-mysql 
        - libmysqlclient21
        - mysql-common 
      


      



    
    